# This file was generated by GoReleaser. DO NOT EDIT.
class Aman < Formula
  desc "aman"
  homepage "https://github.com/naruhiyo/aman"
  version "0.1.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/naruhiyo/aman/releases/download/v0.1.9/aman_darwin_amd64.tar.gz"
    sha256 "ddc8c241b618698638cd47240b0fc9990754b9ab609a0bacd884d55be9fa1aeb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/naruhiyo/aman/releases/download/v0.1.9/aman_linux_amd64.tar.gz"
    sha256 "2874c5257963d81ad7e68761acc8cc4833c6a9b269c2009452823419f987fb0d"
  end

  def install
    bin.install "aman"
  end
end
